version: "3.8"
services:
  cms:
    restart: unless-stopped
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
